<?php
namespace local_subscriptions;
defined('MOODLE_INTERNAL') || die();
use advanced_testcase;use local_subscriptions\commerce\personaloffer\admin\CommercePersonalOfferCrmInput;use local_subscriptions\commerce\personaloffer\campaign\CommercePersonalOfferCampaignManager;use local_subscriptions\commerce\personaloffer\domain\CommercePersonalOfferTerms;
final class commerce_personal_offer_campaign_manager_test extends advanced_testcase {
 public function test_create_list_campaign_and_preview_materialises_members_without_offers(): void {global $DB;$this->resetAfterTest(true);$u=$this->getDataGenerator()->create_user(['email'=>'k8@example.test']);$now=time();$pid=$DB->insert_record('local_subs_commerce_product',(object)['sku'=>'K8TARGET','type'=>'digital','status'=>'active','name'=>'K8 Target','description'=>null,'metadatajson'=>'{}','availablefrom'=>null,'availableuntil'=>null,'timecreated'=>$now,'timemodified'=>$now]);$terms=CommercePersonalOfferTerms::fixed_price(['EUR'=>3000]);$m=CommercePersonalOfferCampaignManager::create($DB);$cid=$m->create_campaign(['campaignkey'=>'k8-list','name'=>'K8 list','audiencetype'=>'list','sourceproductsku'=>null,'targetproductid'=>$pid,'termsversion'=>1,'terms'=>$terms->get_data(),'criteria'=>['list'=>(string)$u->id,'excludeowned'=>false]],(int)$u->id);$summary=$m->preview($cid,(int)$u->id);$this->assertSame(1,$summary['eligible']);$this->assertEquals(0,$DB->count_records('local_subs_commerce_offer'));}
 public function test_preview_then_generate_is_idempotent(): void {global $DB;$this->resetAfterTest(true);$u=$this->getDataGenerator()->create_user(['email'=>'k8b@example.test']);$now=time();$pid=$DB->insert_record('local_subs_commerce_product',(object)['sku'=>'K8TARGETB','type'=>'digital','status'=>'active','name'=>'K8 Target B','description'=>null,'metadatajson'=>'{}','availablefrom'=>null,'availableuntil'=>null,'timecreated'=>$now,'timemodified'=>$now]);$terms=CommercePersonalOfferTerms::percentage_discount(1000);$m=CommercePersonalOfferCampaignManager::create($DB);$cid=$m->create_campaign(['campaignkey'=>'k8-idempotent','name'=>'K8 idem','audiencetype'=>'list','targetproductid'=>$pid,'termsversion'=>1,'terms'=>$terms->get_data(),'criteria'=>['list'=>'k8b@example.test','excludeowned'=>false]],(int)$u->id);$m->preview($cid,(int)$u->id);$m->create_snapshot($cid,(int)$u->id);$m->generate($cid,(int)$u->id);$this->assertSame(1,$DB->count_records('local_subs_commerce_offer'));$m->retry_generation_errors($cid,(int)$u->id);$this->assertSame(1,$DB->count_records('local_subs_commerce_offer'));}
 public function test_crm_amounts_are_entered_in_major_units(): void {
  $this->assertSame('EUR:3000,RUB:299000', CommercePersonalOfferCrmInput::amounts_from_major(['EUR'=>'30.00','RUB'=>'2990']));
 }
 public function test_preview_selection_can_exclude_one_recipient(): void {global $DB;$this->resetAfterTest(true);$u1=$this->getDataGenerator()->create_user(['email'=>'select1@example.test']);$u2=$this->getDataGenerator()->create_user(['email'=>'select2@example.test']);$now=time();$pid=$DB->insert_record('local_subs_commerce_product',(object)['sku'=>'K8SELECT','type'=>'digital','status'=>'active','name'=>'K8 Select','description'=>null,'metadatajson'=>'{}','availablefrom'=>null,'availableuntil'=>null,'timecreated'=>$now,'timemodified'=>$now]);$terms=CommercePersonalOfferTerms::fixed_price(['EUR'=>3000]);$m=CommercePersonalOfferCampaignManager::create($DB);$cid=$m->create_campaign(['campaignkey'=>'k8-selection','name'=>'K8 selection','audiencetype'=>'list','targetproductid'=>$pid,'termsversion'=>1,'terms'=>$terms->get_data(),'criteria'=>['list'=>'select1@example.test select2@example.test','excludeowned'=>false]],(int)$u1->id);$m->preview($cid,(int)$u1->id);$members=$m->members($cid);$m->update_member_selection($cid,[(int)$members[0]->id],(int)$u1->id);$summary=$m->summary($cid);$this->assertSame(1,$summary['eligible']);$this->assertSame(1,$summary['excluded']);}
}
